---
- name: Be sure that VM will start with host when it power on
  command: |
    qm set {{ vm_id }} \
      --onboot 1
  when: start_at_boot == true

- name: Import cloud-init disk previously downloaded
  command: |
    qm set {{ vm_id }} \
    --scsi0 {{ host_config['hw']['hdd_storage_location'] }}:0,import-from={{ locations['working_folder'] }}/{{ qcow2_images[host_config['os']][host_config['version']] | basename }},format=qcow2

- name: Resize disk
  command: |
    qm resize {{ vm_id }} scsi0 {{ host_config['hw']['hdd_size'] }}

- name: Remove disk from temporary folder
  file:
    state: absent
    path: "{{ locations['working_folder'] }}/{{ qcow2_images[host_config['os']][host_config['version']] | basename }}"

- name: Add CD-ROM device for Cloud-Init
  command: |
    qm set {{ vm_id }} \
    --ide2 local-lvm:cloudinit
    
- name: Force boot order
  command: |
    qm set {{ vm_id }} \
    --boot order=scsi0