---
- name: Start virtual machine
  command: |
    qm start {{ vm_id }}

- name: Wait for Cloud-Init end
  wait_for:
    host: "{{ host_config['hw']['network']['ip'] }}"
    port: 22
    delay: 60
    state: present