---
- name: Before first connexion, we remove known IP from file known_hosts (just in case of)
  command: |
    ssh-keygen -f "~/.ssh/known_hosts" -R "{{ host_config['network']['ip'] }}"

- name: Setup Python if not installed
  block:
    - name: Check if Python is installed
      raw: "/bin/bash -c 'test -f {{ python['path'] }}'"
  rescue:
    - name: Setup Python if not installed
      raw: "/bin/bash -c '(apt-get update && apt-get install {{ python['pkg_name'] }}) || (dnf install -y {{ python['pkg_name'] }})'"
  always:
    - name: Gathering Facts
      setup: ~
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Now, setup wanted apps with Aptitude
  apt:
    pkg:
    - qemu-guest-agent
    - python3
    - network-manager
    - nmon
    - telnet
    - mlocate
    - sudo
    - dnsutils
    - vim
    - snmp
    - bash-completion
    - ssh
    - unattended-upgrades
  delegate_to: "{{ host_config['network']['ip'] }}"
  when: os2deploy == "debian" or os2deploy == "ubuntu"

- name: Now, setup wanted apps with Dnf
  apt:
    dnf:
    - qemu-guest-agent
    - python3
    - network-manager
    - nmon
    - telnet
    - mlocate
    - sudo
    - dnsutils
    - vim
    - snmp
    - bash-completion
    - ssh
    - dnf-automatic
  delegate_to: "{{ host_config['network']['ip'] }}"
  when: os2deploy == "rocky"