---
- name: Allow SNMP agent to listen on their primary network interfare (not only localhost)
  lineinfile: 
    path: "{{ snmp_config['conf_location'] }}"
    regexp: "^agentaddress(.*)$"
    line: "agentaddress {{ host_config['network']['ip'] }},127.0.0.1,[::1]"
    backrefs: yes
    backup: "{{ snmp_config['backup_config'] }}"
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Replace RO community IPv4 by our
  lineinfile: 
    path: "{{ snmp_config['conf_location'] }}"
    regexp: "^rocommunity (.*)$"
    line: "rocommunity  {{ snmp_config['rocommunity'] }} default -V systemonly"
    backrefs: yes
    backup: "{{ snmp_config['backup_config'] }}"
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Replace RO community IPv6 by our
  lineinfile: 
    path: "{{ snmp_config['conf_location'] }}"
    regexp: "^rocommunity6(.*)$"
    line: "rocommunity6 {{ snmp_config['rocommunity'] }} default -V systemonly"
    backrefs: yes
    backup: "{{ snmp_config['backup_config'] }}"
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Replace contact information
  lineinfile: 
    path: "{{ snmp_config['conf_location'] }}"
    regexp: "^sysContact(.*)$"
    line: "sysContact     {{ snmp_config['syscontact'] }}"
    backrefs: yes
    backup: "{{ snmp_config['backup_config'] }}"
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Replace location information
  lineinfile: 
    path: "{{ snmp_config['conf_location'] }}"
    regexp: "^sysLocation(.*)$"
    line: "sysLocation    {{ snmp_config['syslocation'] }}"
    backrefs: yes
    backup: "{{ snmp_config['backup_config'] }}"
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Restart and activate SNMP service
  service:
    name: "{{ snmp_config['service_name'] }}"
    state: restarted
    enabled: yes
  delegate_to: "{{ host_config['network']['ip'] }}"