---
- name: Configure SNMP service
  blockinfile:
    path: "{{ snmp_config['conf_location'] }}"
    insertafter: "EOF"
    block: |
      rocommunity {{ snmp_config['rocommunity'] }}
      syscontact {{ snmp_config['syscontact'] }}
    backup: snmp_config['backup_config']

- name: Restart and activate SNMP service
  service:
    name: "{{ snmp_config['service_name'] }}"
    state: restarted
    enabled: yes