---
- name: Change server timezone
  command: |
    timedatectl set-timezone {{ ntp_config['timezone'] }}
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Remove other NTP server
  lineinfile:
    path: "{{ ntp_config['conf_location'][host_config['os']] }}"
    state: absent
    regexp: "^pool(.*)$"
    backup: "{{ ntp_config['backup_config'] }}"
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Set NTP server
  lineinfile: 
    path: "{{ ntp_config['conf_location'][host_config['os']] }}"
    regexp: "^pool(.*)$"
    line: "pool {{ ntp_config['server'] }}"
    backrefs: yes
    backup: "{{ ntp_config['backup_config'] }}"
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Restart and activate NTP service
  service:
    name: "{{ ntp_config['service_name'][host_config['os']] }}"
    state: restarted
    enabled: yes
  delegate_to: "{{ host_config['network']['ip'] }}"