---
- name: Create users
  user:
    name: "{{ item['name'] }}"
    password: "{{ item['password'] }}"
    state: "{{ item['state'] | default('present') }}"
    createhome: "{{ item['createhome'] | default('yes') }}"
  loop: "{{ users_config['users'] }}"
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Get ansible SSH key
  set_fact:
    ansible_ssh_key: "{{ lookup('file', locations['ansible_public_key']) }}"

- name: Allow ansible to ssh this server with created user
  authorized_key:
    user: "{{ item['name'] }}"
    state: present
    key: "{{ ansible_ssh_key }}"
  loop: "{{ users_config['users'] }}"
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Provide sudo rights
  lineinfile:
    path: "/etc/sudoers.d/{{ item['name'] }}"
    line: "{{ item['name'] }} ALL=(ALL) ALL"
    create: yes
  loop: "{{ users_config['users'] }}"
  when:
    - item['name'] != "root" # No need to provide sudo rights to root user...
    - item['sudo']
  delegate_to: "{{ host_config['network']['ip'] }}"