---
- name: Reboot machine and send a message
  reboot:
    msg: "Rebooting machine in 5 seconds"
  delegate_to: "{{ host_config['network']['ip'] }}"

- name: Wait for VM rebooting
  wait_for:
    host: "{{ host_config['network']['ip'] }}"
    port: 22
    delay: 60
    state: present

- name: Display end message
  debug:
    msg: |
      VM created with success !
      Proxmox ID = {{ vm_id }}
      MAC = {{ vm_mac }}"
      IP = {{ host_config['network']['ip'] }}
      Name = {{ host_config['hostname'] }}