---
- name: Working from infos
  debug:
    msg: "Working from {{ inventory_hostname }}: {{ ansible_distribution }} {{ ansible_distribution_major_version }} ({{ ansible_distribution_version }})"

- name: Download cloud-init image
  include_tasks: "01_download_qcow2.yml"

- name: Create VM
  include_tasks: "02_create_vm.yml"

- name: Configure VM hardware
  include_tasks: "03_configure_vm_hw.yml"

- name: Reserve IP on our IPAM
  debug:
    msg: "For a future release"

- name: Create random root password on our password vault
  debug:
    msg: "For a future release"

- name: Configure VM software
  include_tasks: "04_configure_vm_sw.yml"

- name: Start VM
  include_tasks: "05_start_vm.yml"

- name: Setup programs
  include_tasks: "06_setup_programs.yml"

- name: Configure SNMP
  include_tasks: "07_configure_snmp.yml"
  when: snmp_config['configure']

- name: Configure QEMU Agent
  include_tasks: "08_configure_qemu_agent.yml"
  when: qemu_agent_config['configure']

- name: Add VM to our Bastion
  debug:
    msg: "For a future release"