---
- name: Working from infos
  debug:
    msg: "Working from {{ inventory_hostname }}: {{ ansible_distribution }} {{ ansible_distribution_major_version }} ({{ ansible_distribution_version }})"

- name: Download cloud-init image
  include_tasks: "01_download_qcow2.yml"

- name: Create VM
  include_tasks: "02_create_vm.yml"

- name: Configure VM hardware
  include_tasks: "03_configure_vm_hw.yml"

- name: Configure VM software
  include_tasks: "04_configure_vm_sw.yml"

- name: Start VM
  include_tasks: "05_start_vm.yml"